# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34f160f81cd03daf9fa63b6d296db537d9bad756f1844bc81cf5f91200e89862ed82df5c8d403e85db091eed59ff3c08b35aa897779926277cea46a59e48234d

test:
  secret_key_base: 3dbe2dc02268e000c28c8a814f023fb8170570814d9a74efca253a2a15f695b303aa037478c7fa9622aae3f25de79e1a6037273467f8f73247bedba36d4094ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
